七七_thoughts_0: Qiqi is a healer, so her damage is not important. To maximize her damage, a healing bonus circlet is required. Qiqi heals a lot, and because of the ocean-hued clam artifact set, her performance in a Eula physical team is pretty good.
七七_thoughts_1: "Aritfact: Energy recharge / ATK sands, ATK goblet, healing bonus circlet.\nSub stat priority: ATK % > Energy recharge"
七七_符文治療: Talisman Heal
久岐忍_E半血治療: E half HP heal
久岐忍_thoughts_0: Kuki Shinobu is a healer, and the amount of healing you get increases more when you increase her HP instead of her EM, but EM gives you more damage. EM/EM/Heal bonus and HP/HP/Heal bonus have a difference of around 700 HP in terms of heal, so if you like you can bring EM. However even if Kuki brings EM, the catalyze damage is less than 10K, which is less than half of a Xinqiu without buff, so it doesn't make much sense tbh.
久岐忍_thoughts_1: "Artifacts: HP/EM sands, HP/EM goblet, heal bonus circlet\nSub stat: HP % = EM > ER"
九條裟羅_Q吃鳥羽: Q after consuming feather
九條裟羅_thoughts_0: Kujou Sara has decent damage by herself, especially when fighting against large targets. She is a high multiplier character, so it is better to bring an ATK sand. If you need some ER then bring ER sands, considering that she already has ATK buff herself.
九條裟羅_thoughts_1: "Artifacts: ATK/ER sands, Electro DMG goblet, Crit Rate/DMG circlet\nSub stat: Crit Rate/DMG > ATK % > ER"
五郎_Q每次: Q DMG each time
五郎_thoughts_0: Gorou is the easiest character to build, he won't have any damage even if you give him good sub stats. Just level up his E and bring a Favonius bow to give some ER to his teammates, or even The Exile 4 piece to give Itto or Noelle ER. (Since Nobless is not very profitable for Itto and Noelle, The Exile is probably the most profitable artifact set)
五郎_thoughts_1: "Aritacts: Anything, if you bring Favonius you can bring a Crit Rate circlet\nSubstat: Anything"
亞蘿伊_Q滿線圈: Full coil Q
亞蘿伊_thoughts_0: Aloy is a four star under the apperance of a five star, she has no constellation no weapon no teammates. She's an unpopular character, if you really want to build her just bring Blizzard Strayer x4
亞蘿伊_thoughts_1: "Artifacts: ATK sands, Cryo DMG goblet, Crit Rate/DMG circlet\nSub stat: Crit Rate/DMG > ATK % > ER"
余響4件套: Echoes of an Offering x4
優菈_Q13層光劍: 13 stacks Q
優菈_thoughts_0: The only thing you should notice is Physical DMG bonus 170%, Pale Flame x4 + Song of Broken Pines + C1 is excatly 160%.
優菈_thoughts_1: Don't bring ER sands, let her teammates do the ER for her, such as the Raiden Eula Rosaria Qiqi team.
優菈_thoughts_2: "Artifacts: ATK sands, Physical DMG goblet, Crit Rate/DMG circlet\nSub stat: Crit Rate/DMG > ATK % > ER"
八重神子_thoughts_0: Yae Miko should use ATK/Electro/Crit Rate or DMG. If you don't care about her Q damage at C1, then EM sands is better, after C1 she can do one Q per rotation, so ATK sands is better than EM sands. After C2 ATK sands will always be better than EM sands.
八重神子_thoughts_1: "Artifacts: ATK sands, Electro DMG goblet, Crit Rate/DMG circlet\nSub stat: Crit Rate/DMG > ATK % > ER"
八重神子_殺生櫻落雷: Sesshou Sakura thunder DMG
冰風2件套+宗室2件套: Blizzard Strayer x2 + Nobless x2
冰風2件套+角斗2件套: Blizzard Strayer x2 + Gladiator x2
冰風四件套: Blizzard Strayer x4
凝光_Q每顆: Each Q projectile
凝光_thoughts_0: Ningguang lacks team synergy, and she can't outdamage five stars, so she's not very popular right now.
凝光_thoughts_1: 金珀 and Healing circlet can be equipped on Ningguang when teamed with Hu Tao-Xingqiu-Zhongli for Geo resonance and alleviate bleeding damage from 流血狗, especially 黃金王獸. She is also a catalyst user which comes in handy when combatting against 黃金王獸 for its shield.
凝光_thoughts_2: "Recommended artifacts: Damage-related. \nMain stats: ATK% sand, Geo DMG goblet, Crit rate/DMG circlet\nSub stats: Crit rate/DMG > ATK% > ER"
凱亞_Q每段: Each individual Q
凱亞_thoughts_0: Kaeya has a low pick rate, and is mostly used for applying cryo. Damage is not a major priority, so energy recharge should be focused by using 絕緣四.
凱亞_thoughts_1: "Recommended artifacts:\nMain stats: ER%/ATK% sand, Cryo DMG goblet, Crit rate/DMG circlet\nSub stats: Crit rate/DMG > ATK% > ER%"
刻晴_thoughts_0: Although Keqing applies electro well and is suitable for aggregate teams, ATK% sand is still better after calculations.
刻晴_thoughts_1: Keqing was used to melee DMG in the past, but now electro DMG Keqing is stronger with teammates such as Kazuha and Kujoh Sara, and with aggregate reaction. Charged attack knocks enemies back and is time-consuming, using EQE on electro Keqing is wiser.
刻晴_thoughts_2: "Artifact Recommendation: ATK sand, Electro DMG goblet, CR/CD circlet;\nSub-stat Recommendation: CR/CD > ATK % > ER"
刻晴_重擊: Charged attack
北斗_Q閃電鏈: Q閃電鏈
北斗_thoughts_0: 北斗在3.0還是和以前一樣的，不是因為精通收益的問題，而是因為3.0的激化體系不太會選北鬥，因為北鬥需要普攻觸發，和現在激化隊的角色機制有衝突，比如提納里是蓄力箭，刻晴主要靠EQE，計算結果顯示刻晴AZ打得越少越好...... 現在激化隊還是皇女和八重這種完全脫手的雷系會比較合適。
北斗_thoughts_1: '聖遺物思路推薦： 攻擊/充能沙、雷傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>攻擊百分比>元素充能效率'
千岩4件套: 千岩4件套
可莉_thoughts_0: 可莉最受歡迎的玩法是可莉三火，而且可莉因為掛火頻率高，經常會導致輔助來不及掛水，所以純火是比較好的——這意味著可莉並不需要精通。
可莉_thoughts_1: '聖遺物思路推薦： 攻擊沙、火傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊'
可莉_金花重擊蒸發: 金花重擊蒸發
多莉_Q治療每跳: Q治療每跳
多莉_thoughts_0: '多莉是治療輔助的定位，雖然雷傷頻率很高，但附著頻率很低，所以就算想藉用激化打傷害，也是不現實的，專注把功能性搞好就行。 要最大化治療量的話，治療頭是必不可少的，這也是治療型角色通用的結論。 聖遺物思路推薦： 生命/充能沙、生命杯、治療頭 副詞條優先級： 生命百分比>元素充能效率'
夜蘭_Q協同: Q協同
夜蘭_thoughts_0: 夜蘭的傷害只和生命挂鉤，相當於攻擊區了，和心海鐘離又有不同，因為夜蘭的攻擊區就是生命，沒別的東西，所以也不會有水傷更高貴的說法，就和平常一樣。
夜蘭_thoughts_1: 充能方面，夜蘭和行秋或者雷神組會好一些，單掛夜蘭想充起來必須一命，否則充能需求會高到離譜。 正常搭配行秋時充能武器和充能沙二選一，比如若水就充能沙，終末就生命沙。
夜蘭_thoughts_2: 聖遺物思路推薦： 生命/充能沙、水傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴>百分比生命>充能效率
如雷2件套+角斗2件套: 如雷2件套+角斗2件套
如雷4件套: 如雷4件套
安柏_Q總共: Q總共
安柏_thoughts_0: 若安柏蒸發覆蓋率按EQ的40%算，則精通收益始終在暴擊收益以下，此時不推薦堆任何精通。
安柏_thoughts_1: '聖遺物思路推薦： 火傷有就帶 攻擊沙、火傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊'
安柏_蓄力蒸發: 蓄力蒸發
宗室4件套: 宗室4件套
宗室四件套: 宗室四件套
宵宮_thoughts_0: 宵宮蒸發覆蓋率一般認為在50%偏上，圖中是56%。 精通對總傷收益其實並不高，通常精通靠歪就行了，沙漏就帶攻擊沙。 在隊伍中有班尼特或雲堇時，會因為攻擊太多，使得精通在數值更大時仍然比攻擊收益高，存在精通沙更優的情況。 宵宮元素爆發價值一般，所以也不怎麼需要充能效率。
宵宮_thoughts_1: '聖遺物思路推薦： 攻擊沙、火傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊'
宵宮_開E首箭: 開E首箭
少女2件套+千岩2件套: 少女2件套+千岩2件套
少女4件套: Maiden Beloved x4
托馬_thoughts_0: 托馬屬於盾輔角色，並且即使你給托馬堆了攻暴，也打不出多少傷害，上面的圖其實參考價值不大。 托馬的配裝思路比較簡單，就是堆充能和生命保證功能性就可以了。
托馬_thoughts_1: '聖遺物思路推薦： 充能沙、生命杯、生命頭 （帶西風槍時可以用暴擊頭） 副詞條優先順序： 百分比生命=元素充能效率'
托馬_滿層護盾: 滿層護盾
提納里_thoughts_0: '提納里在使用獵人之徑時，精通收益永遠高於攻擊，而其它武器都有攻擊反大於精通的閾值，這個閾值在500-700左右，通常達不到，可以認為提納里就是精通更好。 和草主的解說一樣，草系通常只有杯位會猶豫選精通還是攻擊，杯子和頭是鎖定草杯和暴擊頭的，也有點類似胡桃和鍾離，因為激化是在攻擊區，會和自己本身的面板攻擊相互稀釋，反過來導致增傷和暴擊收益大幅提升，所以一定是草杯+暴擊頭。 提納里的充能在實戰中都可以做到12s一個大，沒必要有太多充能詞條甚至充能沙。 聖遺物思路推薦： 精通/充能沙、草傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>元素精通>百分比攻擊≥充能效率'
提納里_激化藏蘊矢: 激化藏蘊矢
旅行者_Q 每跳激化: Q 每跳激化
旅行者_Q每波: Q每波
旅行者_thoughts_0: 岩主出場率不高，一般都是在娛樂玩法，比如“共鳴流”里會出現，關鍵還是主角這個數值給的有點低。 屬性上比較常規沒什需要特別注意的。
旅行者_thoughts_1: '聖遺物思路推薦： 增傷有就帶，不用擔心稀釋 攻擊沙、岩傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）> 百分比攻擊>元素充能效率'
旅行者_thoughts_2: '聖遺物思路推薦（攻暴流）： 攻擊沙、風傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊>元素充能效率'
旅行者_勾玉充能加成: 勾玉充能加成
旅行者_擴散: 擴散
旗印四件套: 旗印四件套
早柚_Q每次治療: Q每次治療
早柚_thoughts_0: 早柚是治療輔助，攻擊和精通對治療量的收益差不多，自己靈活選擇吧，如果硬要說傷害的話，精通是更好的，但多數人不願意用精通還是因為精通太難刷了，總之攻擊也是不錯的。
早柚_thoughts_1: "Recommended artifacts:\nMain stats: ATK%/ER% sand, ATK%/ER% goblet, 治療 circlet\nSub stats: Crit rate/DMG > ATK% > ER%"
柯萊_Q 每跳激化: Q 每跳激化
柯萊_thoughts_0: '柯萊的攻擊收益其實是高於精通的，可能有些人直覺上會以為精通好。 柯萊要提高傷害應該帶攻擊沙，而不是精通沙，如果缺充能的話，也可以帶充能沙。 柯萊的掛草功能性是比提高自己傷害更加最重要的。 聖遺物思路推薦： 攻擊/充能沙、草傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊>元素充能效率=元素精通'
楓原萬葉_thoughts_0: 楓原萬葉無論從自身傷害出發還是考慮全隊收益，三精通是最優的，尤其是在3.0草元素反應加入后，萬葉造成的雷擴散也能觸發激化（擴激），進一步提高了精通的價值。
楓原萬葉_thoughts_1: '聖遺物思路推薦： 精通沙、精通杯、精通（滿命暴擊/暴傷）頭 副詞條優先順序： 元素精通>元素充能效率'
楓原萬葉_擴散: 擴散
樂團4件套: 樂團4件套
樂團四件套: 樂團四件套
沉淪4件套: 沉淪4件套
沉淪宗室2件套: 沉淪宗室2件套
沉淪角鬥2件套: 沉淪角鬥2件套
海染4件套: 海染4件套
海染四件套: 海染四件套
深林4件套: 深林4件套
溫迪_thoughts_0: After the introduction of aggregate reaction in version 3.0, Venti with full EM build wins over ATK%/Anemo DMG/Crit build completely.
溫迪_thoughts_1: It is recommended to have 170% ER on Venti. ER% sand can be used instead of EM sand if weapon substat have no ER%.
溫迪_thoughts_2: "Recommended artifacts:\nMain stats: ATK%/ER% sand, ATK%/ER% goblet, 治療 circlet\nSub stats: Crit rate/DMG > ATK% > ER%"
溫迪_擴散: Swirl
煙緋_thoughts_0: 煙緋因為重擊、戰技、大招都是單獨組別，所以蒸發覆蓋率非常高，接近100%，在煙莫組合的爆發中就是100%，圖中也是按100%算的。 煙緋的天賦2會使得暴擊率有更高的收益，實際操作的時候多找一些暴擊也是合理的。
煙緋_thoughts_1: "Recommended artifacts:\nMain stats: ATK%/EM sand, Pyro DMG goblet, Crit rate/DMG circlet\nSub stats: Crit rate/DMG > ATK% = EM > ER%"
煙緋_開Q重擊蒸發: 開Q重擊蒸發
珊瑚宮心海_thoughts_0: 1詞條水傷你可以理解成同時影響攻擊和生命兩種屬性，相當於雙倍收益（其實也沒那麼誇張），所以水傷對傷害的提升還是比較明顯的。 心海不管要不要打傷害，都是帶治療頭的。 輔助能力的話，純治療就帶生命杯，不然就水杯，其實帶水杯治療量也不低了。
珊瑚宮心海_thoughts_1: "Recommended artifacts:\nMain stats: HP% sand, Hydro DMG/HP% goblet, HP%/治療 circlet\nSub stats: HP% > Flat HP = ER%"
珊瑚宮心海_水母回血: Jellyfish healing
珊瑚宮心海_開Q普攻: Normal attack during element burst
班尼特_Q治療: Q healing
班尼特_Q蒸發: Q vapourize
班尼特_thoughts_0: 班尼特因為自己大招可以提供高額攻擊加成，所以即使是走傷害流，對攻擊力面板也沒有要求。 事實上更加常見的配裝是充生治，因為充生治里治療加成時固定，能考詞條改變的只有生命，思路比較簡單。
班尼特_thoughts_1: "Recommended artifacts - Support build:\nMain stats: ER%/HP% sand, HP% goblet, 治療 circlet\nSub stats: ER% = HP% > Flat HP"
班尼特_thoughts_2: "Recommended artifacts - DPS build:\nMain stats: ATK%/EM sand, Pyro DMG goblet, Crit rate/DMG circlet\nSub stats: Crit rate/DMG > EM > ATK%"
琴_Q治療: Q healing
琴_thoughts_0: 琴屬於治療輔助，遠古時期可以依靠摔怪單通12層，不過現在的怪都是boss沒法摔了。 琴的傷害是次要的，保證治療量即可。
琴_thoughts_1: "Recommended artifacts:\nMain stats: ATK% sand, ATK% goblet, 治療 circlet\nSub stats: ATK% > ER%"
甘雨_thoughts_0: 甘雨作為冰系而且自帶加暴擊的天賦，通常暴擊率比較高，在挑選詞條的時候暴傷會更加高貴一些。 眾所周知甘雨還有融甘玩法，圖中精通是按100%覆蓋率算的，用於融化蓄力箭的參考。
甘雨_thoughts_1: "Recommended artifacts:\nMain stats: ATK% sand, Cryo DMG goblet, Crit rate/DMG circlet\nSub stats: Crit rate/DMG > ATK% > ER%"
甘雨_霜畫矢綻放: 霜畫矢綻放
甘雨_霜畫矢融化: 霜畫矢融化
申鶴_Q傷害: Q damage
申鶴_thoughts_0: 申鶴的機制比較特殊，說直接點，往死裡堆攻擊就完事了，別的什麼暴擊冰傷不用管。 除非帶西風的時候可以帶個暴擊頭。 申鶴目前只能配神裡綾華，別的都不好，在考慮要不要練申鶴的時候可以考慮一下這點。
申鶴_thoughts_1: 申鶴一般主詞條帶攻攻攻即可，因為主副詞條不能重複，所以三個位置的副詞條第一優先順序就是充能，攻攻攻申鶴靠副詞條弄到170%充能是沒問題的，不需要充能沙。
申鶴_thoughts_2: 套裝使用率最高的是2角2追，因為這套成型快，倉庫里有一堆直接就能用了，但在紙面上宗室4是隊伍總傷最高的。
申鶴_thoughts_3: "Recommended artifacts:\nMain stats: ATK% sand, ATK% goblet, ATK% circlet - Crit rate if 西風 is used\nSub stats: ATK% > ER% > Flat ATK"
砂糖_thoughts_0: 砂糖是風系精通拐，自己精通越高，給隊友的精通buff越強，專注堆精通就可以了。 傷害也是明顯的精通流更高。 砂糖容易缺充能，而大招又比較重要，更多時候會帶充能沙，即使武器是金珀，也會帶充能沙。
砂糖_thoughts_1: "Recommended artifacts:\nMain stats: ER%/EM sand, EM goblet, EM circlet\nSub stats: EM > ER%"
砂糖_擴散: Swirl
磐岩4件套: 磐岩4件套
磐岩宗室2件套: 磐岩宗室2件套
磐岩角鬥2件套: 磐岩角鬥2件套
神里綾人_E首刀+余響/無: E首刀+余響/無
神里綾人_E首刀+沉淪4: E首刀+沉淪4
神里綾人_thoughts_0: 浪閃的作用和心海、鍾離是類似的，相當於自帶一定量的攻擊加成，導致後續堆的攻擊會被稀釋，反過來說暴擊區和增傷區的收益會提高。 綾人要提高傷害的話，攻擊是明顯大於生命的，攻擊對傷害的提升約為生命的1.7倍。
神里綾人_thoughts_1: "Recommended artifacts:\nMain stats: ATK% sand, Hydro DMG goblet, Crit rate/DMG circlet\nSub stats: Crit rate/DMG > ATK% > HP%"
神里綾華_thoughts_0: 神裡不看隊友的時候，攻冰攻傷害算出來是比攻冰暴傷害高的，於是有些人會誤以為神裡攻擊頭更好。 其實，因為神裡能輕鬆吃到討龍、申鶴、宗室這類高額攻擊區buff，最終還是暴傷頭更好的。
神里綾華_thoughts_1: 關於神裡的充能，因為有羅莎莉亞/申鶴的存在，神里其實不缺充能，很快就能被隊友充滿，充能沙是沒必要的。
神里綾華_thoughts_2: "Recommended artifacts:\nMain stats: ATK% sand, Cryo DMG goblet, Crit DMG circlet\nSub stats: Crit DMG > Crit rate > ATK% > ER%"
神里綾華_霜滅切割: 霜滅切割
絕緣4件套: 絕緣4件套
絕緣千岩2件套: 絕緣千岩2件套
翠綠4件套: 翠綠4件套
胡桃_thoughts_0: 通常來講，胡桃不應刻意堆生命。 精通沙相比生命沙的優勢顯然是精通傷害更高，而生命沙的優勢在於，不局限於蒸發，胡桃也是有三火陣容的，另外，聯機的時候往往沒有那麼穩定的掛水，生命沙在你帶萌新打本的時候會更C一點。 生存的話，胡桃都是帶鍾離的多點生命對生存的提升基本是可以忽略的。 （除非你沒鍾離）
胡桃_thoughts_1: '聖遺物思路推薦： 生命/精通沙、火傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比生命=元素精通>百分比攻擊'
胡桃_重擊蒸發: 重擊蒸發
芭芭拉_Q瞬抬: Q瞬抬
芭芭拉_thoughts_0: 芭芭拉以輔助能力為主，要最大化治療量的話，治療頭是必不可少的。 硬要玩戰鬥牧師的話，還是常見的攻擊增傷120%，精通270。
芭芭拉_thoughts_1: 聖遺物思路推薦： 充能/生命沙、生命杯、治療頭 副詞條優先順序： 生命≥充能
芭芭拉_治療預估: 治療預估
荒瀧一斗_thoughts_0: 在分析曲線之前，先來解決一個小問題： 一鬥基礎防禦959，基礎攻擊227 一條防禦詞條的量為1.875%，一條攻擊詞條的量為1.5% 元素爆發防轉攻比例大於100% 959*1.875% >（227+741）*1.5% 所以一鬥一定是防禦收益高於攻擊。
荒瀧一斗_thoughts_1: 再來看圖，防禦閾值僅有100% 不管你怎麼努力都會高出這個值，實際上只要有“雙暴靠找，防禦靠歪”的思想就可以了。 閾值低的原因和胡桃那會算生命的時候一樣，因為都是轉化為攻擊力，所以會受到原本已有攻擊力的稀釋。
荒瀧一斗_thoughts_2: 聖遺物思路推薦： 增傷有就帶，不用擔心稀釋 防禦沙、岩傷杯、暴擊（暴傷）頭
荒瀧一斗_thoughts_3: 副詞條優先順序： 雙暴（自適應） >百分比防禦>百分比攻擊
荒瀧一斗_開Q重擊連斬: 開Q重擊連斬
莫娜_Q暴擊: Q暴擊
莫娜_Q暴擊蒸發: Q暴擊蒸發
莫娜_thoughts_0: 莫娜以輔助增傷為主，自身傷害是次要的。 在保證充能的前提下，可以去補點傷害，但其實也沒必要就是了。 充能提升水傷的效率只有25%，是比較低的，不建議以提高水傷為目的去找充能詞條，充能只要迴圈得起來就不用再找了。 圖中的水傷是以200充能為前提進行計算的，帶充能沙以後很容易就能到這個值
莫娜_thoughts_1: 聖遺物思路推薦： 莫娜增傷區比較高，而且沙漏會帶充能，這時候攻擊杯會更好。 副詞條里充能也不用找太多，一般莫娜是金珀充能沙，充能已經夠了就不用麻煩副詞條了。 充能沙、攻擊杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴>（元素精通）≥攻擊>充能效率
華館4件套: 華館4件套
菲謝爾_thoughts_0: 菲謝爾在3.0激化體系中是比較重要的角色，因為菲謝爾的雷附著頻率比較高，甚至有超越八重神子傷害的可能。 但菲謝爾仍然是攻擊沙>精通沙，沒有精通轉增傷之類的機制的話，攻擊優於精通屬於比較常見的結論，目前的雷系都符合這個規律。
菲謝爾_thoughts_1: 菲謝爾飾金4總傷更高的原因是因為飾金4給的屬性多，和精通收益是不搭界的，2+2隻有15增傷和18攻擊，但是飾金4能給14攻擊和180精通，它給的實在太多了
菲謝爾_thoughts_2: '聖遺物思路推薦： 攻擊沙、雷傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>攻擊百分比>元素充能效率'
菲謝爾_奧茲攻擊: 奧茲攻擊
蒼白四件套: 蒼白四件套
蒼白騎士2件套: 蒼白騎士2件套
蘿莎莉亞_Q每段: Q每段
蘿莎莉亞_thoughts_0: 羅莎莉亞因為自身機制完美契合精5西風，並且大招可以持續掛冰，不僅能為冰C提供大量充能微粒，還可以配合心海這樣的角色做到十秒以上的凍結，顯著地改善了隊伍充能和容錯，目前來講表現不錯。
蘿莎莉亞_thoughts_1: 羅莎莉亞是輔助的定位，自身傷害不是很重要，可以多堆一些暴擊穩定觸發西風和提高暴擊buff數值。
蘿莎莉亞_thoughts_2: 聖遺物思路推薦： 充能/攻擊沙、冰傷杯、暴擊頭 副詞條優先順序： 暴率>暴傷>攻擊百分比>元素充能效率
行秋_Q劍雨: Q劍雨
行秋_thoughts_0: 行秋雖然大招80能量，但是因為祭禮雙E直接10個水球，加上祭禮是61.3的充能，絕緣套又有20充能，大部分隊算出來也是180能夠，所以實際上行秋是可以不帶充能沙的。
行秋_thoughts_1: 聖遺物思路推薦： 攻擊沙、水傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴>百分比攻擊>充能效率
角斗2件套+追憶2件套: 角斗2件套+追憶2件套
角斗士4件套: 角斗士4件套
諾艾爾_thoughts_0: 首先明確一點——諾艾爾防禦比攻擊收益高。 防禦的曲線如果沒有別的屬性干擾的話，應該是和物傷一樣的，閾值170。 而諾艾爾閾值只有125%，明顯變低了，原因和胡桃、一鬥一樣，因為有防轉攻，所以會受到原本已有攻擊力的稀釋。 換個角度說，就是岩傷和雙暴的收益對諾艾爾非常高。
諾艾爾_thoughts_1: '聖遺物思路推薦： 增傷有就帶，不用擔心稀釋 防禦/充能沙、岩傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應） >百分比防禦>元素充能效率'
諾艾爾_高達首刀: 高達首刀
辛焱_E盾值: E盾值
辛焱_Q橫掃: Q橫掃
辛焱_thoughts_0: 辛焱要走傷害流的話，通常是打物理輸出，火傷比較少，也更不會去打蒸發，所以這裡索性就不放精通曲線了。 在沒有鍾離的時候，辛焱可以作為比較優秀的盾輔，此時主要堆防禦以提高盾量即可。
辛焱_thoughts_1: 6命有50%防禦轉攻擊（僅限重擊），辛焱防禦白值799，攻擊白值249，加上武器暫取800白值。 顯然，就算主打重擊，要堆攻擊就直接堆攻擊好了，防禦提升攻擊的效率只有一半，所以辛焱要提高傷害，還是得靠攻擊
辛焱_thoughts_2: 聖遺物思路推薦（輔助向）： 防禦沙、防禦杯、防禦頭 副詞條優先順序： 百分比防禦力>固定防禦力
辛焱_thoughts_3: 聖遺物思路推薦（傷害向）： 攻擊沙、物傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊力>百分比防禦力
辰砂4件套: 辰砂4件套
迪奧娜_thoughts_0: 迪奧娜是功能非常齊全的輔助角色，能治療能套盾能充電能加精通能掛冰...... 在遊戲前期，尤其是當你用甘雨神裡這類冰系主C時，會有很棒的表現。 以功能性為主，一般更加看中盾值所以帶生生生。
迪奧娜_thoughts_1: 聖遺物思路推薦： 生命沙、生命杯、生命/治療頭 副詞條優先順序： 生命加成>充能效率
迪奧娜_長E盾值: 長E盾值
迪盧克_Q蒸發: Q蒸發
迪盧克_thoughts_0: 姥爺因為大部分攻擊是預設組別，蒸發覆蓋率並不是很高，只有在裝備狼末時，因為攻擊特別高，才是帶精通沙更好。 但如果看的不是總傷，而是大數字的話（覆蓋算100%），精通在接近300之前都是收益較高的。
迪盧克_thoughts_1: '聖遺物思路推薦： 火傷有就帶 攻擊/精通沙、火傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）> 百分比攻擊'
追憶4件套: 追憶4件套
達達利亞_thoughts_0: 公子在蒸發中屬於強勢元素，要持續蒸發是極其困難的，圖中精通是為核爆做參考，相當於蒸發覆蓋率100%。 雖然公子自己不會主動堆精通，但在萬達國際中，有時一刀的爆發的傷害佔比會很高，這時候萬葉二命的提升就會非常大。
達達利亞_thoughts_1: 聖遺物思路推薦： 攻擊沙、水傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊>元素精通=元素充能效率
達達利亞_近戰Q蒸發: 近戰Q蒸發
重雲_Q每段: Q每段
重雲_thoughts_0: 重雲的高光主要是在傳統國家隊，但雷神的出現讓現在的重雲很是難受。 在國家隊里重雲是可以打一波吃班融化的，這裡給出的精通是按100%覆蓋率算的，用於給大數位做參考。
重雲_thoughts_1: 重雲還可以在胡行鐘體系中，利用二命的減CD達到無縫迴圈不卡手的效果，這時候重雲當個掛件就行了裝備都可以不要，胡桃DPS夠了。 重雲的冰附魔在國家隊里可以做到行秋滅火→重雲凍結→香菱蒸發的combo，冰附魔在對陣水使徒和雷使徒時也有較好的效果——總之重雲不是特別吃裝備。
重雲_thoughts_2: 聖遺物思路推薦： 攻擊沙、冰傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊>元素充能效率
鍾離_E實際盾量: E實際盾量
鍾離_Q開盾天星: Q開盾天星
鍾離_thoughts_0: 鍾離作為全體瓦特最具安全感的男人，當然是以盾輔思路為主，這時候可以生生生+黑纓槍，成本低效果好。 除了所謂“血牛鍾離”，還有追求天星傷害的玩法，圖中的生命收益就是對於天星傷害而言的。 可以看到，生命對傷害的收益較低，原因和胡桃一樣，因為這會和已有的攻擊相互稀釋，反過來也意味著岩傷和雙暴對鍾離收益很高。
鍾離_thoughts_1: '聖遺物思路推薦： 生命沙、生命/岩傷杯、生命/暴擊（暴傷）頭 副詞條優先順序： （雙暴）>百分比生命>固定生命'
阿貝多_E剎那之花: E剎那之花
阿貝多_thoughts_0: 阿貝多的傷害絕大部分都來自於元素戰技的協同攻擊，有時候甚至會嫌阿貝多大招動畫浪費時間就把Q扣了，阿貝多的話主堆防禦就行了，攻擊可以不管。
阿貝多_thoughts_1: 阿貝多防禦閾值還是比較高的，現在依靠華館4和辰砂加上防禦沙，就可以達到閾值附近，安心帶暴擊頭就行了，以前還可能會考慮防禦頭。
阿貝多_thoughts_2: 聖遺物思路推薦： 增傷有就帶，不用擔心稀釋 防禦沙、岩傷杯、暴擊（暴傷）頭
阿貝多_thoughts_3: 副詞條優先順序： 雙暴（自適應）> 百分比防禦>百分比攻擊
雲堇_thoughts_0: 雲堇和申鶴十分相似，往死裡堆防禦就可以了。 帶了防防防以後因為主副詞條不能重複，沙杯冠最優先的副詞條就是充能，這樣下來靠副詞條搞到170充能是很正常的，再加上雲堇一般帶西風或者十文字，雲堇是沒必要充能沙的。 帶西風的時候可以選擇暴擊頭。
雲堇_thoughts_1: '聖遺物思路推薦： 防禦沙、防禦杯、防禦（西風時暴擊）頭 副詞條優先順序： 百分比防禦>元素充能效率'
雲堇_任意: 任意
雷澤_thoughts_0: 雷澤屬於萌新之友，大劍角色前期普攻倍率比較高，不容易刮痧，而且長按E在前期傷害很高，範圍大，無論是拍礦還是打怪都很猛。 後期實在是卷不過，打不了深淵。 雷澤是物理C，新手的時候可能會覺得這個E傷害好高，刷了雷杯，其實帶了物理以後體驗更好
雷澤_thoughts_1: 聖遺物思路推薦： 攻擊沙、物傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>攻擊百分比>元素充能效率
雷澤_普攻第一段: 普攻第一段
雷電將軍_thoughts_0: 稻光雷神1詞條充能對傷害的提升在沒有溢出時高於1詞條攻擊或增傷; 不是稻光的話就不如攻擊增傷。 然後絕大多數情況都是雷杯好，畢竟雷國雷九這種標準體系都是帶班的。
雷電將軍_thoughts_1: 聖遺物思路推薦： 充能沙、雷傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>攻擊百分比>元素充能效率
雷電將軍_thoughts_2: '[詳情](https://bbs.nga.cn/read.php?tid=28370182)'
雷電將軍_無想的一刀: 無想的一刀
飾金4件套: 飾金4件套
香菱_Q踩班蒸發: Q踩班蒸發
香菱_thoughts_0: 香菱的蒸發覆蓋率在實戰里就是接近100%的，這裡也是按100%算。 因為香菱的隊友統計中，班尼特出場率達到了95%，可以認為香菱就是綁定班尼特出場了。 班尼特的buff相當於130%左右的攻擊加成，這樣一來，香菱自己的面板上，就沒必要堆攻擊了，可以帶充能沙或者精通沙。
香菱_thoughts_1: '聖遺物思路推薦： 充能/精通沙、火傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>元素精通>元素充能效率>百分比攻擊'
魈_thoughts_0: 魈是攻暴流風C，因為大招能夠提供高達90+的增傷，所以魈的攻擊區是收益比較高的，曾經還有過風杯攻擊杯之爭，但現在有了辰砂套，提供高額攻擊力，就一定是帶風杯了。
魈_thoughts_1: 魈的充能比較關鍵，還是比較有用的，一般會帶琴或者砂糖給魈充電，但魈還是有必要自己帶點充能詞條的，但充能沙不必了，副詞條裡注意一下就行。
魈_thoughts_2: '聖遺物思路推薦： 攻擊沙、風傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊>元素充能效率'
魈_開大首插: 開大首插
魔女4件套: 魔女4件套
鹿野院平藏_E 滿蓄力: E 滿蓄力
鹿野院平藏_thoughts_0: 小鹿不屬於高頻低倍率的風系，自身倍率很高，所以要走攻暴流。 充能方面，自身大招只有40能量而且四命自帶回能，基本不需要什麼充能詞條。
鹿野院平藏_thoughts_1: '聖遺物思路推薦： 攻擊沙、風傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>百分比攻擊>元素充能效率'
麗莎_Q每段: Q每段
麗莎_thoughts_0: 麗莎阿..姐姐這個突破加精通很迷，自己E倍率上千，搞個突破加精通我真不知道啥意思，E的高倍率和Q的高頻率兩種優勢不管怎麼樣都要放棄一個。 總的來說還是攻擊沙更好一點。
麗莎_thoughts_1: '聖遺物思路推薦： 攻擊沙、雷傷杯、暴擊（暴傷）頭 副詞條優先順序： 雙暴（自適應）>攻擊百分比>元素充能效率'
麗莎_滿層E: 滿層E
